
/*Lucio da Cruz de Moraes RA: 2476550*/
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LUCIO
 */
public class CadAntiht extends javax.swing.JFrame {

    /**
     * Creates new form CadAntiht
     */
    public CadAntiht() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLimpar = new javax.swing.JButton();
        ctQuant = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblEfad = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        cbAntiInfla = new javax.swing.JCheckBox();
        ctNome = new javax.swing.JTextField();
        cbAntiT = new javax.swing.JCheckBox();
        lblLote = new javax.swing.JLabel();
        lblClasseTerapeutica = new javax.swing.JLabel();
        ctLote = new javax.swing.JTextField();
        ctClasseTerapeutica = new javax.swing.JTextField();
        lblDatadeValidade = new javax.swing.JLabel();
        lblPressaoAlvo = new javax.swing.JLabel();
        ctDatadeValidade = new javax.swing.JTextField();
        ctPressaoAlvo = new javax.swing.JTextField();
        lblAdmim = new javax.swing.JLabel();
        ctAdmim = new javax.swing.JTextField();
        lblQuant = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        Principio_Ativo = new javax.swing.JLabel();
        ctPrincipio_Ativo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        ctQuant.setText("Ex:10");
        ctQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctQuantActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Imunosupressor");

        lblEfad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEfad.setText("Efeitos Adversos:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setText("NOME:");

        cbAntiInfla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbAntiInfla.setText("Anti-inflamatório");
        cbAntiInfla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAntiInflaActionPerformed(evt);
            }
        });

        ctNome.setText("Nome Anti hipertensão");

        cbAntiT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbAntiT.setText("Anti-termico");
        cbAntiT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAntiTActionPerformed(evt);
            }
        });

        lblLote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLote.setText("Lote:");

        lblClasseTerapeutica.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblClasseTerapeutica.setText("Classe Terapeutica");

        ctLote.setText("2023001");
        ctLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctLoteActionPerformed(evt);
            }
        });

        ctClasseTerapeutica.setText("EX: IECA");
        ctClasseTerapeutica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctClasseTerapeuticaActionPerformed(evt);
            }
        });

        lblDatadeValidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDatadeValidade.setText("Data de Validade:");

        lblPressaoAlvo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPressaoAlvo.setText("Pressão Alvo em mmHG");

        ctDatadeValidade.setText("aaaa/mm/dd");
        ctDatadeValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctDatadeValidadeActionPerformed(evt);
            }
        });

        ctPressaoAlvo.setText("Ex: 4 ");
        ctPressaoAlvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPressaoAlvoActionPerformed(evt);
            }
        });

        lblAdmim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdmim.setText("Administração:");

        ctAdmim.setText("Oral/Ingetável/tópica");
        ctAdmim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctAdmimActionPerformed(evt);
            }
        });

        lblQuant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuant.setText("Quantidade:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        Principio_Ativo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Principio_Ativo.setText("Principio Ativo");

        ctPrincipio_Ativo.setText("Principio Ativo");
        ctPrincipio_Ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPrincipio_AtivoActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Principio_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctPrincipio_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblLote)
                                    .addGap(18, 18, 18)
                                    .addComponent(ctLote))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdmim, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ctAdmim, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btLimpar)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton1)
                                        .addGap(112, 112, 112)
                                        .addComponent(btSair))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblPressaoAlvo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblClasseTerapeutica, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ctClasseTerapeutica, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ctPressaoAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEfad)
                                .addGap(18, 18, 18)
                                .addComponent(cbAntiInfla)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAntiT)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLote)
                    .addComponent(ctLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatadeValidade)
                    .addComponent(ctDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Principio_Ativo)
                    .addComponent(ctPrincipio_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmim)
                    .addComponent(ctAdmim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuant)
                    .addComponent(ctQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfad)
                    .addComponent(cbAntiInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAntiT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClasseTerapeutica)
                    .addComponent(ctClasseTerapeutica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPressaoAlvo)
                    .addComponent(ctPressaoAlvo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void ctQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctQuantActionPerformed

    private void cbAntiInflaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAntiInflaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAntiInflaActionPerformed

    private void cbAntiTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAntiTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAntiTActionPerformed

    private void ctLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctLoteActionPerformed

    private void ctClasseTerapeuticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctClasseTerapeuticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctClasseTerapeuticaActionPerformed

    private void ctDatadeValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctDatadeValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctDatadeValidadeActionPerformed

    private void ctPressaoAlvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPressaoAlvoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPressaoAlvoActionPerformed

    private void ctAdmimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctAdmimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctAdmimActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void ctPrincipio_AtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPrincipio_AtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPrincipio_AtivoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cadastrar();
    }//GEN-LAST:event_jButton1ActionPerformed
       
    public void limpar() {
    ctNome.setText("");
    ctLote.setText("");
    ctDatadeValidade.setText("aaaa-mm-dd");
    ctPrincipio_Ativo.setText("");
    ctAdmim.setText("");
    ctQuant.setText("");
    cbAntiInfla.setSelected(false);
    cbAntiT.setSelected(false);
        ctClasseTerapeutica.setText("");
        ctPressaoAlvo.setText("");
}
    private void cadastrar(){
        Anti_Hipertensivo antiHtensao = new Anti_Hipertensivo();
        try{
        antiHtensao.setNome(ctNome.getText());
        antiHtensao.setLote(Integer.parseInt(ctLote.getText()));
        try{
            antiHtensao.setData_Validade(LocalDate.parse(ctDatadeValidade.getText()));
         }catch(DateTimeParseException d){
                    JOptionPane.showMessageDialog(
				null,
				"Formato de data não suportado"	);
                }
        antiHtensao.setPrincipio_Ativo(ctPrincipio_Ativo.getText());
        antiHtensao.setAdministracao(ctAdmim.getText());
        EfeitosAdversos efad=new EfeitosAdversos();
        efad.setEf_Analgesico(cbAntiInfla.isSelected());
        efad.setEf_Anti_Termico(cbAntiT.isSelected());
        antiHtensao.setEFAD(efad);
        antiHtensao.setClasse_Terapeutica(ctClasseTerapeutica.getText());
        antiHtensao.setPressao_Alvo(Integer.parseInt(ctPressaoAlvo.getText()));
        antiHtensao = BDFarmacia.getBDFarmacia().addAnti_Htensao(antiHtensao);
        }catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(
				null,
				"Voce inseriu algum dado de forma incorreta!");
                              
        }
        if(antiHtensao!=null){
            JOptionPane.showMessageDialog(
                        null,
                       "Remedio Cadastrado");
            limpar();
    }
    else{
            JOptionPane.showMessageDialog(
                            null,
                            "Cadastro não efetuado"); 
    }
        limpar();
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAntiht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAntiht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAntiht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAntiht.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAntiht().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Principio_Ativo;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JCheckBox cbAntiInfla;
    private javax.swing.JCheckBox cbAntiT;
    private javax.swing.JTextField ctAdmim;
    private javax.swing.JTextField ctClasseTerapeutica;
    private javax.swing.JTextField ctDatadeValidade;
    private javax.swing.JTextField ctLote;
    private javax.swing.JTextField ctNome;
    private javax.swing.JTextField ctPressaoAlvo;
    private javax.swing.JTextField ctPrincipio_Ativo;
    private javax.swing.JTextField ctQuant;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAdmim;
    private javax.swing.JLabel lblClasseTerapeutica;
    private javax.swing.JLabel lblDatadeValidade;
    private javax.swing.JLabel lblEfad;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblPressaoAlvo;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
