/* Lucio da Cruz de Moraes*/
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
public class CadAntiAler extends javax.swing.JFrame {

    /**
     * Creates new form CadAntiAler
     */
    public CadAntiAler() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblNivelSup = new javax.swing.JLabel();
        ctLote = new javax.swing.JTextField();
        ctAlergeno = new javax.swing.JTextField();
        lblDatadeValidade = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblGeracao = new javax.swing.JLabel();
        lblEfad = new javax.swing.JLabel();
        ctDatadeValidade = new javax.swing.JTextField();
        lblNome = new javax.swing.JLabel();
        ctGeracao = new javax.swing.JTextField();
        cbAntiInfla = new javax.swing.JCheckBox();
        lblAdmim = new javax.swing.JLabel();
        ctNome = new javax.swing.JTextField();
        cbAntiT = new javax.swing.JCheckBox();
        ctAdmim = new javax.swing.JTextField();
        lblLote = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        lblQuant = new javax.swing.JLabel();
        ctQuant = new javax.swing.JTextField();
        btCadastar = new javax.swing.JButton();
        Principio_Ativo = new javax.swing.JLabel();
        ctPrincipio_Ativo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblNivelSup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNivelSup.setText("Alergeno:");

        ctLote.setText("2023001");
        ctLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctLoteActionPerformed(evt);
            }
        });

        ctAlergeno.setText("Ex: Picada de Inseto");
        ctAlergeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctAlergenoActionPerformed(evt);
            }
        });

        lblDatadeValidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDatadeValidade.setText("Data de Validade:");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Anti-Alergico");

        lblGeracao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblGeracao.setText("Geração:");

        lblEfad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEfad.setText("Efeitos Adversos:");

        ctDatadeValidade.setText("aaaa/mm/dd");
        ctDatadeValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctDatadeValidadeActionPerformed(evt);
            }
        });

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setText("NOME:");

        ctGeracao.setText("Ex: 4 ");
        ctGeracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctGeracaoActionPerformed(evt);
            }
        });

        cbAntiInfla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbAntiInfla.setText("Anti-inflamatório");
        cbAntiInfla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAntiInflaActionPerformed(evt);
            }
        });

        lblAdmim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdmim.setText("Administração:");

        ctNome.setText("Nome Anti-Alergico");

        cbAntiT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbAntiT.setText("Anti-termico");
        cbAntiT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAntiTActionPerformed(evt);
            }
        });

        ctAdmim.setText("Oral/Ingetável/tópica");
        ctAdmim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctAdmimActionPerformed(evt);
            }
        });

        lblLote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLote.setText("Lote:");

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        lblQuant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuant.setText("Quantidade:");

        ctQuant.setText("Ex:10");
        ctQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctQuantActionPerformed(evt);
            }
        });

        btCadastar.setText("Cadastrar");
        btCadastar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastarActionPerformed(evt);
            }
        });

        Principio_Ativo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Principio_Ativo.setText("Principio Ativo");

        ctPrincipio_Ativo.setText("Principio Ativo");
        ctPrincipio_Ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPrincipio_AtivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblLote)
                                    .addGap(18, 18, 18)
                                    .addComponent(ctLote))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblNome)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Principio_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ctPrincipio_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblNivelSup, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ctAlergeno))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblGeracao)
                                            .addGap(24, 24, 24)
                                            .addComponent(ctGeracao, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ctQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblAdmim, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ctAdmim, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEfad)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAntiInfla)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbAntiT))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btCadastar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLote)
                    .addComponent(ctLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatadeValidade)
                    .addComponent(ctDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Principio_Ativo)
                    .addComponent(ctPrincipio_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmim)
                    .addComponent(ctAdmim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuant)
                    .addComponent(ctQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfad)
                    .addComponent(cbAntiInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAntiT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelSup)
                    .addComponent(ctAlergeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctGeracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGeracao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(jButton1)
                    .addComponent(btCadastar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ctLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctLoteActionPerformed

    private void ctAlergenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctAlergenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctAlergenoActionPerformed

    private void ctDatadeValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctDatadeValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctDatadeValidadeActionPerformed

    private void ctGeracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctGeracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctGeracaoActionPerformed

    private void cbAntiInflaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAntiInflaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAntiInflaActionPerformed

    private void cbAntiTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAntiTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAntiTActionPerformed

    private void ctAdmimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctAdmimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctAdmimActionPerformed

    private void ctQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctQuantActionPerformed

    private void btCadastarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btCadastarActionPerformed

    private void ctPrincipio_AtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPrincipio_AtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPrincipio_AtivoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    public void limpar() {
    ctNome.setText("");
    ctLote.setText("");
    ctDatadeValidade.setText("aaaa-mm-dd");
    ctPrincipio_Ativo.setText("");
    ctAdmim.setText("");
    ctQuant.setText("");
    cbAntiInfla.setSelected(false);
    cbAntiT.setSelected(false);
    ctAlergeno.setText("");
    ctGeracao.setText("");
}

    private void cadastrar(){
	Anti_Alergico antialer = new Anti_Alergico();
        try{
                antialer.setNome(ctNome.getText());
		antialer.setLote(Integer.parseInt(ctLote.getText()));
                try{
                    antialer.setData_Validade(LocalDate.parse(ctDatadeValidade.getText()));
                }catch(DateTimeParseException d){
                    JOptionPane.showMessageDialog(
				null,
				"Formato de data não suportado"	);
                }
		antialer.setPrincipio_Ativo(ctPrincipio_Ativo.getText());
		antialer.setAdministracao(ctAdmim.getText());
                EfeitosAdversos efad=new EfeitosAdversos();
                efad.setEf_Analgesico(cbAntiInfla.isSelected());
                efad.setEf_Anti_Termico(cbAntiT.isSelected());
                antialer.setEFAD(efad);
                antialer.setAlergeno(ctAlergeno.getText());
                antialer.setGeracao(Integer.parseInt(ctGeracao.getText()));
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(
				null,
				"Voce inseriu algum dado de forma incorreta!");
        }
	
	antialer = BDFarmacia.getBDFarmacia().addAnti_Alergico(antialer);
	if(antialer!=null){
		JOptionPane.showMessageDialog(
				null,
				"Cadastro efetuado com sucesso!");
		limpar();
	}
	else{
		JOptionPane.showMessageDialog(
				null,
				"Cadastro não efetuado!"	); 
	}
} 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadAntiAler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadAntiAler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadAntiAler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadAntiAler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadAntiAler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Principio_Ativo;
    private javax.swing.JButton btCadastar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JCheckBox cbAntiInfla;
    private javax.swing.JCheckBox cbAntiT;
    private javax.swing.JTextField ctAdmim;
    private javax.swing.JTextField ctAlergeno;
    private javax.swing.JTextField ctDatadeValidade;
    private javax.swing.JTextField ctGeracao;
    private javax.swing.JTextField ctLote;
    private javax.swing.JTextField ctNome;
    private javax.swing.JTextField ctPrincipio_Ativo;
    private javax.swing.JTextField ctQuant;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblAdmim;
    private javax.swing.JLabel lblDatadeValidade;
    private javax.swing.JLabel lblEfad;
    private javax.swing.JLabel lblGeracao;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblNivelSup;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
