/*Lucio da Cruz de Moraes*/
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LUCIO
 */
public class CadImunosupressor extends javax.swing.JFrame {

    /**
     * Creates new form CadImunosupressor
     */
    public CadImunosupressor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btLimpar = new javax.swing.JButton();
        ctQuant = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        lblEfad = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        cbAntiInfla = new javax.swing.JCheckBox();
        ctNome = new javax.swing.JTextField();
        cbAntiT = new javax.swing.JCheckBox();
        lblLote = new javax.swing.JLabel();
        lblNivelSup = new javax.swing.JLabel();
        ctLote = new javax.swing.JTextField();
        ctNivelSup = new javax.swing.JTextField();
        lblDatadeValidade = new javax.swing.JLabel();
        lblFreqInfec = new javax.swing.JLabel();
        ctDatadeValidade = new javax.swing.JTextField();
        ctFreqInfec = new javax.swing.JTextField();
        lblAdmim = new javax.swing.JLabel();
        lblDurSup = new javax.swing.JLabel();
        ctAdmim = new javax.swing.JTextField();
        ctDurSup = new javax.swing.JTextField();
        lblQuant = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        Principio_Ativo = new javax.swing.JLabel();
        ctPrincipio_Ativo = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        ctQuant.setText("Ex:10");
        ctQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctQuantActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("Imunosupressor");

        lblEfad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEfad.setText("Efeitos Adversos:");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNome.setText("NOME:");

        cbAntiInfla.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbAntiInfla.setText("Anti-inflamatório");
        cbAntiInfla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAntiInflaActionPerformed(evt);
            }
        });

        ctNome.setText("Nome Imunosupressor");

        cbAntiT.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbAntiT.setText("Anti-termico");
        cbAntiT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAntiTActionPerformed(evt);
            }
        });

        lblLote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLote.setText("Lote:");

        lblNivelSup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNivelSup.setText("Nivel de Supressão:");

        ctLote.setText("2023001");
        ctLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctLoteActionPerformed(evt);
            }
        });

        ctNivelSup.setText("Ex: Moderado");
        ctNivelSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNivelSupActionPerformed(evt);
            }
        });

        lblDatadeValidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDatadeValidade.setText("Data de Validade:");

        lblFreqInfec.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFreqInfec.setText("Frequencia de infecções em semanas:");

        ctDatadeValidade.setText("aaaa/mm/dd");
        ctDatadeValidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctDatadeValidadeActionPerformed(evt);
            }
        });

        ctFreqInfec.setText("Ex: 4 ");
        ctFreqInfec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctFreqInfecActionPerformed(evt);
            }
        });

        lblAdmim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdmim.setText("Administração:");

        lblDurSup.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDurSup.setText("Duração da Supressão em semanas:");

        ctAdmim.setText("Oral/Ingetável/tópica");
        ctAdmim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctAdmimActionPerformed(evt);
            }
        });

        ctDurSup.setText("Ex:4");
        ctDurSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctDurSupActionPerformed(evt);
            }
        });

        lblQuant.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuant.setText("Quantidade:");

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        Principio_Ativo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Principio_Ativo.setText("Principio Ativo");

        ctPrincipio_Ativo.setText("Principio Ativo");
        ctPrincipio_Ativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctPrincipio_AtivoActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btCadastrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btSair))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAdmim, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ctAdmim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(ctQuant)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblEfad)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbAntiInfla)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbAntiT))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblFreqInfec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNivelSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDurSup, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ctNivelSup, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ctFreqInfec, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(ctDurSup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(ctDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblLote)
                                            .addGap(18, 18, 18)
                                            .addComponent(ctLote))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblNome)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Principio_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ctPrincipio_Ativo)))
                                .addGap(0, 56, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLote)
                    .addComponent(ctLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatadeValidade)
                    .addComponent(ctDatadeValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Principio_Ativo)
                    .addComponent(ctPrincipio_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdmim)
                    .addComponent(ctAdmim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuant)
                    .addComponent(ctQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEfad)
                    .addComponent(cbAntiInfla, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAntiT))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNivelSup)
                    .addComponent(ctNivelSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFreqInfec)
                    .addComponent(ctFreqInfec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDurSup)
                    .addComponent(ctDurSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair)
                    .addComponent(btCadastrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limpar();
    }//GEN-LAST:event_btLimparActionPerformed

    private void ctQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctQuantActionPerformed

    private void cbAntiInflaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAntiInflaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAntiInflaActionPerformed

    private void cbAntiTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAntiTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbAntiTActionPerformed

    private void ctLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctLoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctLoteActionPerformed

    private void ctNivelSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNivelSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctNivelSupActionPerformed

    private void ctDatadeValidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctDatadeValidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctDatadeValidadeActionPerformed

    private void ctFreqInfecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctFreqInfecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctFreqInfecActionPerformed

    private void ctAdmimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctAdmimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctAdmimActionPerformed

    private void ctDurSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctDurSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctDurSupActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void ctPrincipio_AtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctPrincipio_AtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctPrincipio_AtivoActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_btCadastrarActionPerformed
private void limpar() {
    ctNome.setText("");
    ctLote.setText("");
    ctDatadeValidade.setText("aaaa-mm-dd");
    ctPrincipio_Ativo.setText("");
    ctAdmim.setText("");
    ctQuant.setText("");
    cbAntiInfla.setSelected(false);
    cbAntiT.setSelected(false);
    ctNivelSup.setText("");
    ctFreqInfec.setText("");
    ctDurSup.setText("");
}

    private void cadastrar(){
	Imunosupressor imuno = new Imunosupressor();
        imuno.setNome(ctNome.getText());
        imuno.setLote(Integer.parseInt(ctLote.getText()));
        try{
            imuno.setData_Validade(LocalDate.parse(ctDatadeValidade.getText()));
         }catch(DateTimeParseException d){
                    JOptionPane.showMessageDialog(
				null,
				"Formato de data não suportado"	);
                }
        imuno.setPrincipio_Ativo(ctPrincipio_Ativo.getText());
        imuno.setAdministracao(ctAdmim.getText());
        EfeitosAdversos efad=new EfeitosAdversos();
        efad.setEf_Analgesico(cbAntiInfla.isSelected());
        efad.setEf_Anti_Termico(cbAntiT.isSelected());
        imuno.setEFAD(efad);
        imuno.setNivel_Supressao(Integer.parseInt(ctNivelSup.getText()));
        imuno.setFreq_Infeccoes(Integer.parseInt(ctFreqInfec.getText()));
        imuno.setDuracao_Supressao(Integer.parseInt(ctDurSup.getText()));
	imuno = BDFarmacia.getBDFarmacia().addImunosupressor(imuno);
	if(imuno!=null){
		JOptionPane.showMessageDialog(
				null,
				"Cadastro efetuado com sucesso!");
		limpar();
	}
	else{
		JOptionPane.showMessageDialog(
				null,
				"Cadastro não efetuado!"	); 
	}
         limpar();
} 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadImunosupressor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadImunosupressor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadImunosupressor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadImunosupressor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadImunosupressor().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Principio_Ativo;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JCheckBox cbAntiInfla;
    private javax.swing.JCheckBox cbAntiT;
    private javax.swing.JTextField ctAdmim;
    private javax.swing.JTextField ctDatadeValidade;
    private javax.swing.JTextField ctDurSup;
    private javax.swing.JTextField ctFreqInfec;
    private javax.swing.JTextField ctLote;
    private javax.swing.JTextField ctNivelSup;
    private javax.swing.JTextField ctNome;
    private javax.swing.JTextField ctPrincipio_Ativo;
    private javax.swing.JTextField ctQuant;
    private javax.swing.JLabel lblAdmim;
    private javax.swing.JLabel lblDatadeValidade;
    private javax.swing.JLabel lblDurSup;
    private javax.swing.JLabel lblEfad;
    private javax.swing.JLabel lblFreqInfec;
    private javax.swing.JLabel lblLote;
    private javax.swing.JLabel lblNivelSup;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQuant;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
